import type { WeatherSnapshot } from "./weather";

// CloudSentinel integration layer: live forecast screening + clearly labelled demo scenarios.
export type Severity = "Low" | "Moderate" | "High" | "Critical";
export type SensorStatus = "Normal" | "Warning" | "Anomaly" | "Sensor Fault" | "Corrected";
export interface WeatherObservation { temperature: number; humidity: number; pressureMsl: number; windSpeed: number; windGusts: number; precipitation: number; cloudCover: number; observedAt: number; source: "Live Open-Meteo" | "Demo simulation"; }
export interface ForecastRisk { hazard: string; severity: Severity; confidence: number; period: string; onset: string; measurements: string[]; explanation: string; source: "Live forecast analysis" | "Demo simulation"; }
export interface SensorHealth { name: string; status: SensorStatus; value: string; quality: "Healthy" | "Suspect" | "Faulty" | "Corrected"; }
export interface AnomalyResult { sensor: string; observed: string; estimated?: string; status: string; confidence?: number; reconstructionMse?: number; threshold?: number; reason: string; integration: "Demo adapter" | "Model integration pending" | "Live model"; }
export interface Explanation { factor: string; direction: "up" | "down"; detail: string; source: "Demo adapter" | "Model integration pending" | "Live model"; }
export interface AffectedAsset { name: string; type: string; latitude: number; longitude: number; distanceKm: number; exposure: string; risk: Severity; }
export interface CloudSentinelAssessment { observation: WeatherObservation; forecast: ForecastRisk; sensors: SensorHealth[]; anomaly?: AnomalyResult; explanation: Explanation[]; assets: AffectedAsset[]; isDemo: boolean; }

const sampleAssets: AffectedAsset[] = [
  { name: "North logistics hub", type: "Logistics facility", latitude: 0.012, longitude: 0.008, distanceKm: 1.4, exposure: "Loading operations and low-lying access routes", risk: "High" },
  { name: "Grid substation", type: "Critical infrastructure", latitude: -0.018, longitude: 0.012, distanceKm: 2.3, exposure: "Exposed power equipment and access", risk: "High" },
  { name: "Industrial storage park", type: "Industrial facility", latitude: 0.021, longitude: -0.017, distanceKm: 3.1, exposure: "Drainage and stored-material exposure", risk: "Moderate" },
];

const sensorRows = (observation: WeatherObservation): SensorHealth[] => [
  { name: "Temperature", status: "Normal", value: `${observation.temperature.toFixed(1)} °C`, quality: "Healthy" },
  { name: "Humidity", status: "Normal", value: `${observation.humidity.toFixed(0)}%`, quality: "Healthy" },
  { name: "MSL pressure", status: "Normal", value: `${observation.pressureMsl.toFixed(0)} hPa`, quality: "Healthy" },
  { name: "Wind", status: "Normal", value: `${observation.windSpeed.toFixed(0)} km/h`, quality: "Healthy" },
  { name: "Precipitation", status: "Normal", value: `${observation.precipitation.toFixed(1)} mm`, quality: "Healthy" },
  { name: "Cloud cover", status: "Normal", value: `${observation.cloudCover.toFixed(0)}%`, quality: "Healthy" },
];

export function assessmentFromLive(snapshot: WeatherSnapshot): CloudSentinelAssessment {
  const totalRain = snapshot.hourly.reduce((sum, hour) => sum + hour.precipitation, 0);
  const maxWind = Math.max(snapshot.windGusts, ...snapshot.hourly.map((hour) => hour.windSpeed));
  const hazard = totalRain >= 25 ? "Heavy Rainfall Risk" : maxWind >= 55 ? "High Wind Risk" : snapshot.apparentTemperature >= 40 ? "Heat Risk" : "No elevated forecast risk";
  const severity: Severity = totalRain >= 40 || maxWind >= 70 ? "Critical" : totalRain >= 25 || maxWind >= 55 || snapshot.apparentTemperature >= 40 ? "High" : totalRain >= 10 || maxWind >= 40 ? "Moderate" : "Low";
  const onsetReading = snapshot.hourly.find((hour) => hour.precipitation > 1 || hour.windSpeed >= 40);
  const observation: WeatherObservation = { temperature:snapshot.temperature, humidity:snapshot.humidity, pressureMsl:snapshot.pressureMsl, windSpeed:snapshot.windSpeed, windGusts:snapshot.windGusts, precipitation:snapshot.precipitation, cloudCover:snapshot.cloudCover, observedAt:snapshot.observedAt, source:"Live Open-Meteo" };
  return { observation, isDemo:false, sensors:sensorRows(observation), forecast:{ hazard, severity, confidence: severity === "Low" ? 78 : 80, period:"Next 24 hours", onset:onsetReading ? new Intl.DateTimeFormat("en-GB", {hour:"2-digit",minute:"2-digit",hour12:false,timeZone:snapshot.timezone}).format(new Date(onsetReading.time)) : "No elevated window identified", measurements:[`${totalRain.toFixed(1)} mm forecast precipitation`, `Gusts currently ${snapshot.windGusts.toFixed(0)} km/h`, `Cloud cover ${snapshot.cloudCover.toFixed(0)}%`], explanation: severity === "Low" ? "Forecast conditions remain within the configured local screening thresholds." : "Forecast conditions exceed a screening threshold. This is a potential hazard condition, not a prediction of damage.", source:"Live forecast analysis" }, explanation:[{factor:"Model contributors",direction:"up",detail:"SHAP contributors will appear after the ML endpoint provides them.",source:"Model integration pending"}], assets: severity === "Low" ? [] : sampleAssets };
}

export const demoScenarios: Record<string, CloudSentinelAssessment> = {
  normal: { ...assessmentFromLive({ location:{name:"Demo location",latitude:0,longitude:0}, observedAt:Date.now(), timezone:"UTC",timezoneAbbreviation:"UTC",temperature:29.6,apparentTemperature:30,humidity:61,precipitation:0,rain:0,windSpeed:9,windGusts:15,windDirection:0,pressure:1012,pressureMsl:1014,cloudCover:28,weatherCode:1,isDay:true,hourly:[] }), isDemo:true },
  rain: { observation:{temperature:31.8,humidity:76,pressureMsl:1004,windSpeed:18,windGusts:34,precipitation:1.2,cloudCover:72,observedAt:Date.now(),source:"Demo simulation"}, isDemo:true, sensors:[], forecast:{hazard:"Heavy Rainfall Risk",severity:"High",confidence:87,period:"Next 3 hours",onset:"Expected from 11:30",measurements:["18.6 mm expected","Wind gusts up to 42 km/h","Cloud cover 94%"],explanation:"Forecast precipitation is above the local short-term baseline. This is an early warning, not a flood prediction.",source:"Demo simulation"},explanation:[{factor:"Precipitation",direction:"up",detail:"Forecast accumulation is elevated for this time window.",source:"Demo adapter"},{factor:"MSL pressure",direction:"down",detail:"Pressure trend supports unsettled conditions.",source:"Demo adapter"},{factor:"Wind gusts",direction:"up",detail:"Increasing gusts can compound local exposure.",source:"Demo adapter"}],assets:sampleAssets },
  wind: { observation:{temperature:30.2,humidity:65,pressureMsl:1007,windSpeed:31,windGusts:58,precipitation:0.4,cloudCover:68,observedAt:Date.now(),source:"Demo simulation"},isDemo:true,sensors:[],forecast:{hazard:"High Wind Risk",severity:"High",confidence:84,period:"Next 4 hours",onset:"Expected from 12:15",measurements:["Gusts up to 61 km/h","Sustained wind 35 km/h","Cloud cover 78%"],explanation:"Forecast wind gusts exceed the local operational threshold. This indicates potential exposure, not guaranteed damage.",source:"Demo simulation"},explanation:[{factor:"Wind gusts",direction:"up",detail:"Forecast gusts exceed the local warning band.",source:"Demo adapter"},{factor:"Wind speed",direction:"up",detail:"Sustained wind is elevated.",source:"Demo adapter"}],assets:sampleAssets },
  sensor: { observation:{temperature:118,humidity:64,pressureMsl:1011,windSpeed:10,windGusts:16,precipitation:0,cloudCover:34,observedAt:Date.now(),source:"Demo simulation"},isDemo:true,sensors:[],forecast:{hazard:"No elevated forecast risk",severity:"Low",confidence:81,period:"Next 6 hours",onset:"No elevated window identified",measurements:["0 mm expected","Wind below 18 km/h","Cloud cover 34%"],explanation:"Forecast is stable. AWS quality controls isolate the temperature spike before downstream hazard assessment.",source:"Demo simulation"},anomaly:{sensor:"Temperature",observed:"118 °C",estimated:"32.4 °C (estimated)",status:"Likely sensor fault",confidence:96,reason:"Abrupt deviation from the learned pattern and inconsistency with humidity, pressure and recent readings.",integration:"Demo adapter"},explanation:[{factor:"Temperature deviation",direction:"up",detail:"Observed reading is outside the learned normal pattern.",source:"Demo adapter"},{factor:"Humidity relationship",direction:"down",detail:"Humidity does not support an extreme heat observation.",source:"Demo adapter"}],assets:[] },
  multiple: { observation:{temperature:39.8,humidity:82,pressureMsl:998,windSpeed:38,windGusts:68,precipitation:15.4,cloudCover:96,observedAt:Date.now(),source:"Demo simulation"},isDemo:true,sensors:[],forecast:{hazard:"Severe weather conditions",severity:"Critical",confidence:89,period:"Next 3 hours",onset:"Expected from 10:45",measurements:["31 mm expected","Gusts up to 68 km/h","Temperature 40 °C"],explanation:"Multiple forecast parameters are elevated. Review local emergency procedures and field observations.",source:"Demo simulation"},explanation:[{factor:"Precipitation",direction:"up",detail:"Heavy forecast accumulation in a short interval.",source:"Demo adapter"},{factor:"Wind gusts",direction:"up",detail:"Gusts exceed the high-wind threshold.",source:"Demo adapter"},{factor:"MSL pressure",direction:"down",detail:"Pressure is materially below the recent baseline.",source:"Demo adapter"}],assets:sampleAssets },
};
for (const scenario of Object.values(demoScenarios)) if (scenario.sensors.length === 0) scenario.sensors = sensorRows(scenario.observation);
